buymeanoodle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('creator/', include('creator.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

creator/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'creator'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='creator/login.html'), name='login'),
    path('creators/', views.creators, name='creators'),
    path('edit/', views.edit, name='edit'),
]

core/models.py
from django.db import models

# Create your models here.

creator/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.

class Creator(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='uploads/creators/', blank=True, null=True)
    user = models.OneToOneField(User, related_name='creator', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

creator/forms.py
from django.forms import ModelForm

from .models import Creator

class CreatorForm(ModelForm):
    class Meta:
        model = Creator
        fields = ('title', 'description', 'image',)

core/views.py
from django.shortcuts import render, redirect

from creator.models import Creator

# Create your views here.

def index(request):
    creators = Creator.objects.all()
    if request.user.is_authenticated:
        try:
            creator = request.user.creator
        except Exception as e:
            return redirect('creator:edit')
    return render(request, 'core/index.html', {
        'creators': creators
    })

creator/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .models import Creator
from .forms import CreatorForm

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created successfully')
            return redirect('creator:login')
    else:
        form = UserCreationForm()
    return render(request, 'creator/signup.html', {
        'form': form
    })

def creators(request):
    creators = Creator.objects.all()
    return render(request, 'creator/creators.html', {
        'creators': creators
    })

def edit(request):
    # if request.method == 'POST':
    #     form = CreatorForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         messages.success(request, 'Page edited successfully')
    # else:
    #     form = CreatorForm()
    try:
        creator = request.user.creator
        if request.method == 'POST':
            form = CreatorForm(request.POST, request.FILES, instance=creator)

            if form.is_valid():
                form.save()

                return redirect('core:index')
        else:
            form = CreatorForm(instance = creator)
    except Exception as e:
        if request.method == 'POST':
            form = CreatorForm(request.POST, request.FILES)

            if form.is_valid():
                creator = form.save(commit = False)
                creator.user = request.user
                creator.save()

                return redirect('core:index')
        else:
            form = CreatorForm()

    return render(request, 'creator/edit.html', {
        'form': form
    })

core/templates/core/base.html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="cryptomus" content="5acb68e1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <title>{% block title %}{% endblock %} | Buy_Me_A_Noodle</title>
</head>
<body class="bg-slate-700">
    <nav class="py-8 px-8 bg-slate-900 flex flex-row items-center justify-between">
      <div>
        <a href="{% url 'core:index' %}" class="text-2xl text-cyan-500 font-bold">Buy Me A Noodle</a>
      </div>

      <div class="space-x-6"> 
        <a href="{% url 'creator:creators' %}" class="py-4 px-6 text-lg text-cyan-500 font-bold">Creators</a>
        {% if not request.user.is_authenticated %}
          <a href="{% url 'creator:login' %}" class="py-4 px-6 text-lg bg-sky-600 hover:bg-sky-700 rounded-xl text-white font-bold">Log In</a>
          <a href="{% url 'creator:signup' %}" class="py-4 px-6 bg-gray-600 hover:bg-gray-700 rounded-xl text-lg text-white font-bold">Sign Up</a>
        {% endif %}
      </div>
    </nav>
    <mainc class="py-6 px-8">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="px-8 py-6 text-center bg-slate-600">
      <p class="text-slate-200">Copyright (c) 2024 - Buy Me A Noodle</p>
    </footer>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}
  Home
{% endblock %}

{% block content %}
  <!-- <h1 class="text-3xl text-white font-bold underline">
    Hello world!
  </h1> -->
  <div class="py-20 text-center space-y-12">
    <h1 class="text-7xl text-slate-300 font-bold">Get Paid For Your Work</h1>

    <a href="#" class="py-8 px-12 inline-block text-xl text-white bg-sky-800 rounded-lg">Create Page</a>
  </div>

  <div class="py-12 bg-slate-800">
    <h2 class="mb-12 text-5xl text-slate-300 text-center font-bold">Newest Creators</h2>

    <div class="px-12 grid grid-cols-4 gap-8">
      {% for creator in creators %}
        <div class="bg-slate-600 rounded-lg">
            <figure>
                <img src="{{ creator.image.url }}" class="rounded-tr-lg rounded-tl-lg" alt="">
            </figure>

            <div class="py-6 px-8 space-y-6">
                <h3 class="text-xl text-slate-200 font-bold">{{ creator.title }}</h3>

                <p class="text-slate-300">{{ creator.description }}</p>

                <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-xl">Read More</a>
            </div>
        </div>
    {% endfor %}
    </div>
  </div>
{% endblock %}

creator/templates/creator/creators.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}
  Creators
{% endblock %}

{% block content %}
  <!-- <h1 class="text-3xl text-white font-bold underline">
    Hello world!
  </h1> -->
  <div class="py-20 text-center space-y-12">
    <h1 class="text-7xl text-slate-300 font-bold">Creators</h1>

    <!-- <a href="#" class="py-8 px-12 inline-block text-xl text-white bg-sky-800 rounded-lg">Create Page</a> -->
  </div>

  <div class="py-12 bg-slate-800">
    <!-- <h2 class="mb-12 text-5xl text-slate-300 text-center font-bold">Newest Creators</h2> -->
    <div class="px-12 grid grid-cols-4 gap-8">
    {% for creator in creators %}
        <div class="bg-slate-600 rounded-lg">
            <figure>
                <img src="{{ creator.image.url }}" class="rounded-tr-lg rounded-tl-lg" alt="">
            </figure>

            <div class="py-6 px-8 space-y-6">
                <h3 class="text-xl text-slate-200 font-bold">{{ creator.title }}</h3>

                <p class="text-slate-300">{{ creator.description }}</p>

                <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-xl">Read More</a>
            </div>
        </div>
    {% endfor %}
</div>
</div>
{% endblock %}

creator/templates/creator/edit.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}
  Edit
{% endblock %}

{% block content %}
  <!-- <h1 class="text-3xl text-white font-bold underline">
    Hello world!
  </h1> -->
  <div class="py-20 text-center space-y-12">
    <h1 class="text-7xl text-slate-300 font-bold">Edit</h1>

    <!-- <a href="#" class="py-8 px-12 inline-block text-xl text-white bg-sky-800 rounded-lg">Create Page</a> -->
  </div>

  <div class="py-12 bg-slate-800 text-black">
    <form action="." method="post" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}

        <div>
            <button class="w-full py-6 px-8 bg-sky-800 text-white font-bold rounded-xl">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

creator/templates/creator/login.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Log In{% endblock %}

{% block content %}
<div class="py-20 text-center space">
    <h1 class="text-7xl text-slate-300 font-bold">Log In</h1>
</div>

<div class="max-w-lg mx-auto py-12 px-8 bg-slate-800">
    <form action="." method="post" class="space-y-6">

        {% csrf_token %}

        <div class="space-y-4">
            <label for="id_username" class="text-lg text-white">Username:</label>

            <input type="text" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="username" id="id_username">
        </div>

        <div class="space-y-4">
            <label for="id_password" class="text-lg text-white">Password:</label>

            <input type="password" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="password" id="id_password">
        </div>
        <br>
        {% if form.errors %}
            <div class="py-6 px-8 bg-amber-600 text-white rounded-lg">
                <p>Username or Password is not correct!</p>
            </div>
        {% endif %}
        <br>
        <div>
            <button class="w-full py-6 px-8 bg-sky-800 text-white font-bold rounded-xl">Submit</button>
        </div>

    </form>
</div>
{% endblock %}

creator/templates/creator/signup.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="py-20 text-center space">
    <h1 class="text-7xl text-slate-300 font-bold">Log In</h1>
</div>

<div class="max-w-lg mx-auto py-12 px-8 bg-slate-800">
    <form action="." method="post" class="space-y-6">

        {% csrf_token %}

        <div class="space-y-4">
            <label for="id_username" class="text-lg text-white">Username:</label>

            <input type="text" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="username" id="id_username">
        </div>

        <div class="space-y-4">
            <label for="id_password1" class="text-lg text-white">Password:</label>

            <input type="password" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="password1" id="id_password1">
        </div>
        <div class="space-y-4">
            <label for="id_password2" class="text-lg text-white">Repeat Password:</label>

            <input type="password" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="password2" id="id_password2">
        </div>
        <br>
        {% if form.errors %}
            <div class="py-6 px-8 bg-amber-600 text-white rounded-lg">
                <p>Username or Password is not correct!</p>
            </div>
        {% endif %}
        <br>
        <div>
            <button class="w-full py-6 px-8 bg-sky-800 text-white font-bold rounded-xl">Submit</button>
        </div>

    </form>
</div>
{% endblock %}